[package]
name = "zero"
version = "0.1.0"
edition = "2021"

authors = ["Noboru Okazaki <johnny.shaman.saxophonist@gamil.com>"]

[dependencies]
docopt = "0.6"
llvm-sys = "*"
regex = "*"
regex_macros = "*"
rustc-serialize = "0.3"
